name: lint

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        versions:
          - 59
        python-version:
          - "3.10"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install VapourSynth
        uses: Irrational-Encoding-Wizardry/install-vapoursynth-action@v0.1
        with:
          version: ${{ matrix.versions }}
          cache: true
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install vapoursynth-portable==${{ matrix.versions }}
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Running flake8
        run: |
          flake8 vstools
          flake8 tests
      - name: Running mypy
        continue-on-error: true
        run: |
          mypy vstools
          mypy tests
      - name: Running tests
        run: pytest tests
