name: lint

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        versions:
          - 68
        python-version:
          - '3.12'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install vapoursynth-portable==${{ matrix.versions }}
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install --force git+https://github.com/Setsugennoao/stgpytools.git
      - name: Running flake8
        run: |
          flake8 vstools
          flake8 tests
      - name: Running mypy
        run: |
          echo "::add-matcher::.github/workflows/matchers/mypy.json"
          mypy --no-pretty vstools
          mypy --no-pretty tests
          echo "::remove-matcher owner=mypy::"
        continue-on-error: true
      - name: Smoke test
        run: python -c "import vstools; print(vstools.core.core)"
